name: C++

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libavcodec-dev libavformat-dev libavformat-dev
      - name: Setup Boost environment variable
        run: echo "::set-env name=BOOST_ROOT::$BOOST_ROOT_1_72_0"
      - name: Run CMake
        run: |
          cmake -S . -B build
          cmake --build build -j 2
